### ISSUE TITLE
Upgrade to Python3.6

### ISSUE THREAD

**Issue by tjrivera** [chop-dbhi/ehb-service#10]
The rest of the biorepository toolkit runs Python3. We should also upgrade this application to python 3.x.

**Comment by seg1129** [comment]
@alexanderkgonzalez - Which python3 version do you suggest we upgrade the eHB to?

**Comment by szh2425** [comment]
Update: 

- Was mostly running tests for ehb's core before without the api. But ran tests for core and api recently and the error messages from api are helpful in understanding what needs to be in bytes and what can stay as a string during encryption. 

TL;DR I think I'll be able to have this down in 1-2 weeks

**Comment by szh2425** [comment]
11/16/2018 Update: 

**My understanding of EHB encryption/decryption in Python2:**
_Encryption_
1. We get value from fixtures as string: **ex. ‘John’**
2. We encode to bytes: **ex. b’John';** `(get_db_prep_value() in encryptionFields.py)`
3. We encrypt via pycryptodome aes: **ex. x00@1-j{3(}4i]** `(encrypt() in encryptionServices.py)`
4. We convert encryption into hexstring: **ex. ‘d8b774de4d15d8**’ `(get_db_prep_value() in encryptionFields.py)`

_Decryption_
1. We get value from database as hex string: **ex.  ‘d8b774de4d15d8’** `(from_db_value () in encryptionFields.py)`
2. We unhexify the hex string: **ex.  x00@1-j{3(}4i]**  `(to_python() in encryptionFields.py)`
3. We decrypt via pycryptodome: **ex. b'John'** (decrypt () in encryptionServices.py)`
4. We decode to string: **ex. ‘John’**  `(to_python() in encryptionFields.py)`


 **What I think needs to occur for EHB encryption/decryption in Python3** 
_Encryption_
1. We get value from fixtures as string: **ex. ‘John’**
2. We encode to bytes, **ex. b’John’;** 
3. We encrypt via pycryptodome aes, **ex. b'\xd8\xb7t\xdeM\x15\**
4. We convert encryption into hex, which is bytes, **ex. b'd8b774de4d15d8**
5. ***** We decode hexabytes to string: **ex.  ‘d8b774de4d15d8’** 

_Decryption_
1. We get value from database as hex string: **ex.  ‘d8b774de4d15d8’**
2. ****We encode that to bytes: **ex. b‘d8b774de4d15d8’**
3. We unhexify **ex. b'\xd8\xb7t\xdeM\x15\**
4. We decrypt via pycryptodome aes, **ex. b’John’**
5. We decode to string, **ex. ‘John’**

Issues: EncryptionFields.py is confusing because there's a BaseClass that inherits EncryptCharField and EncryptDateField. The methods: to_python and get_db_prep_value appear in both the Base and child classes, and it becomes unclear which method is being used for the unhexify/hexify, encrypt/decrypt.

**Comment by szh2425** [comment]
**12/19/2018 Update:**

EHB runs on Python3 in branch `Issue10_Python3` . Notes:
1. All existing data in ehb postgres database is unable to be decrypted because the hexadecimal values stored on the database need to be updated. The values currently stored are based on pycrypto encryption library. Due to deprecation, in Python3, we switch to using the pycryptodome library. 
2. I tested that the new encryption library works by creating a new subject on the BRP using python3 and pycryptodome. The new subject information is able to be correctly decrypted. 

**Please see attachedscreenshot for visual!** 

![screen shot 2018-12-19 at 12 45 07 pm](https://user-images.githubusercontent.com/33664901/50238284-f3acbe80-038c-11e9-9b02-b53c8f8ac722.png)

 
@seg1129 Do you have any ideas on how we should handle the old data?

**Comment by alexanderkgonzalez** [comment]
Planning to migrate all utf8 encoding and decoding functions to same set of functions\locations.
